//  Auth management
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//  User Management
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ROLE = 'UPDATE_USER_ROLE';
export const USERS_LOADING = 'USERS_LOADING';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

//  Tickets management
export const GET_TICKET = 'GET_TICKET';
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL';
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';
export const GET_TICKETS = 'GET_TICKETS';
export const TICKETS_LOADING = 'TICKETS_LOADING';
export const TICKET_LOADING = 'TICKET_LOADING';
export const GET_TICKETS_FAIL = 'GET_TICKETS_FAIL';
export const ADD_TICKET = 'ADD_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL';
export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR';
export const ADD_REPLY = 'ADD_REPLY';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';
export const DELETE_REPLY = 'DELETE_REPLY';
export const DELETE_REPLY_FAIL = 'DELETE_REPLY_FAIL';
export const CLEAR_TICKET = 'CLEAR_TICKET';
export const COMPLETED_TICKET = 'COMPLETED_TICKET';
export const UPDATE_ASSIGNED_TO = 'UPDATE_ASSIGNED_TO';
//  Projects Management
export const GET_PROJECTS = 'GET_PROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
